apiVersion: v1
kind: Service
metadata:
  name: {{ include "trm-eth-explorer.fullname" . }}
  labels:
    {{- include "trm-eth-explorer.labels" . | nindent 4 }}
  annotations:
    # L4 NLB for the MVP. The L7 path (ALB Ingress + WAF/TLS) is the prod upgrade.
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
spec:
  type: LoadBalancer
  selector:
    {{- include "trm-eth-explorer.selectorLabels" . | nindent 4 }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: http
