{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "trm-eth-explorer.serviceAccountName" . }}
  labels:
    {{- include "trm-eth-explorer.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.roleArn }}
  annotations:
    # IRSA: binds this ServiceAccount to a least-privilege IAM role (unused for the MVP).
    eks.amazonaws.com/role-arn: {{ . }}
  {{- end }}
{{- end }}
